### ISSUE TITLE
Something Corrupted Tile Creation ie Ortho4XP AND macOS Ventura Security issues

### ISSUE THREAD

**Issue by OldSubSailor** [Ortho4XP/Ortho4XP#60]
I attempted to create at tile a few days ago and it had 11 Gig of custom ZL 19 zones. I tried to get a discussion going on the X-Plane.org forum but it never got anywhere.
The output text from X-Plane (and level 3 verbosity was no better) was:
From Ortho4XP 1.30 output text window

  Converting orthophoto(s) to build texture 108464_64864_GO218.dds.
 *Download of textures completed.
 *DDS conversion of textures completed.
 *Activating DSF file.
ERROR : could not rename DSF file, tile is not actived.

The terminal output was:
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/BigHDD/Ortho4XP-master/./src/O4_DSF_Utils.py", line 575, in build_dsf
    tri_p.extend((idx_dsfpool,pos_in_pool))
OverflowError: unsigned short is greater than maximum

From that point on I could never create a tile in that area.  29 -91 i.e. southern coastal Louisiana. I used Ortho4 to delete the entire tile and tried again and got the results above. I deleted the entire Homebrew software and python software and Ortho4, reinstalled and created tiles elsewhere but could not create a tile there (but I was silly enough to all a lot of ZL 19s) and even with no Custom ZLs got the same fails.  It looks like Ortho4XP was corrupted for that tile somehow and remained corrupted even after the tile was deleted. 

Finally I downloaded another Ortho4, installed it inside X-Plane 11 directory & recreated a new X-Plane Custom Scenery directory, left Ortho4 at default settings except for airports and was able to create the tile. 

Another point that macOS Ventura security impacts each new install of Orthos4XP. It stops Triangles, Extraction and the last step of DSF.  One has to pull up System Settings>Privacy & Security and allow it after pressing Cancel on the popup box.

**Comment by d41k4n** [comment]
https://forums.x-plane.org/index.php?/forums/topic/292454-unusual-error-being-caused-by-a-single-tile-area-update-and-yet-another-update/

**Comment by OldSubSailor** [comment]
I can no longer reproduce this error. I believe that is because I can _also no longer_ create Custom Zoom Levels.
